on:
  push:
    tags:
      - '*'
name: Handle Release
jobs:
  generate-installer:
    name: Create release-artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install wix
        run: dotnet tool install --global wix --version 4.0.0
      - name: Build Installer
        run: wix build GridfinityGenerator.wxs -o dist/GridfinityGenerator-${{ github.ref_name }}.msi
      - name: Create zip
        uses: vimtor/action-zip@v1
        with:
          files: GridfinityGenerator.manifest GridfinityGenerator.py config.py LICENSE.md lib/ commands/ documentation/PRIVACY_POLICY.md
          recursive: false
          dest: dist/GridfinityGenerator-${{ github.ref_name }}.zip
      - name: Upload the artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
          body: TBD
          prerelease: true
  generate-zip:
    name: Create zip file for manual installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create zip
        uses: vimtor/action-zip@v1
        with:
          files: GridfinityGenerator.manifest GridfinityGenerator.py LICENSE.md lib/ commands/ documentation/PRIVACY_POLICY.md
          recursive: true
          dest: GridfinityGenerator.zip